# ===================================
#  Relation Behavior Config
# ===================================

property_groups:
    label: 'webbook.mall::lang.common.property_group'
    deferredBinding: false
    view:
        list: $/webbook/mall/models/propertygroup/columns_pivot_legacy.yaml
        toolbarButtons: add|remove
        recordUrl: '/webbook/mall/propertygroups/update/:id'
    manage:
        form: $/webbook/mall/models/propertygroup/fields_no_relation.yaml
        list: $/webbook/mall/models/propertygroup/columns.yaml
    structure:
        showTree: false
        showReorder: true
        showSorting: true
        dragRow: true

products:
    label: 'webbook.mall::lang.common.product'
    view:
        list: $/webbook/mall/models/product/columns.yaml
        recordsPerPage: 10
        recordUrl: webbook/mall/products/update/:id
    readOnly: true
    structure:
        showTree: false
        showReorder: true
        maxDepth: 1

review_categories:
    label: 'webbook.mall::lang.common.review_category'
    view:
        list: $/webbook/mall/models/reviewcategory/columns.yaml
        recordsPerPage: 10
        toolbarButtons: add|create|remove|delete
    manage:
        form: $/webbook/mall/models/reviewcategory/fields.yaml
        list: $/webbook/mall/models/reviewcategory/columns.yaml
