name: 'webbook.mall::lang.common.category'
modelClass: WebBook\Mall\Models\Category
form: $/webbook/mall/models/category/fields.yaml
defaultRedirect: webbook/mall/categories
create:
    title: 'webbook.mall::lang.titles.categories.create'
    redirect: 'webbook/mall/categories/update/:id'
    redirectClose: webbook/mall/categories
update:
    title: 'webbook.mall::lang.titles.categories.update'
    redirect: webbook/mall/categories
    redirectClose: webbook/mall/categories
preview:
    title: 'webbook.mall::lang.titles.categories.preview'
