title: 'webbook.mall::lang.common.categories'
modelClass: WebBook\Mall\Models\Category
list: $/webbook/mall/models/category/columns.yaml
recordUrl: 'webbook/mall/categories/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
structure:
    showTree: true
    showReorder: true
    treeExpanded: true
    maxDepth: 0
