name: 'webbook.mall::lang.common.order_states'
modelClass: WebBook\Mall\Models\OrderState
form: $/webbook/mall/models/orderstate/fields.yaml
defaultRedirect: webbook/mall/orderstate
create:
    title: 'webbook.mall::lang.titles.order_states.create'
    redirect: 'webbook/mall/orderstate/update/:id'
    redirectClose: webbook/mall/orderstate
update:
    title: 'webbook.mall::lang.titles.order_states.edit'
    redirect: webbook/mall/orderstate
    redirectClose: webbook/mall/orderstate
