title: 'webbook.mall::lang.product.properties'
modelClass: WebBook\Mall\Models\Property
list: $/webbook/mall/models/property/columns.yaml
recordUrl: 'webbook/mall/properties/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
