name: 'webbook.mall::lang.product.properties'
modelClass: WebBook\Mall\Models\Property
form: $/webbook/mall/models/property/fields.yaml
defaultRedirect: webbook/mall/properties
create:
    title: 'webbook.mall::lang.titles.properties.create'
    redirect: 'webbook/mall/properties/update/:id'
    redirectClose: webbook/mall/properties
update:
    title: 'webbook.mall::lang.titles.properties.edit'
    redirect: webbook/mall/properties
    redirectClose: webbook/mall/properties
