# ===================================
#  Relation Behavior Config
# ===================================

addresses:
    label: 'webbook.mall::lang.common.address'
    manage:
        form: $/webbook/mall/models/address/fields.yaml
        list: $/webbook/mall/models/address/columns.yaml
    view:
        list: $/webbook/mall/models/address/columns.yaml
        toolbarButtons: create|delete
