name: webbook.mall::lang.common.payment_methods
modelClass: WebBook\Mall\Models\PaymentMethod
form: $/webbook/mall/models/paymentmethod/fields.yaml
defaultRedirect: webbook/mall/paymentmethods
create:
    title: 'webbook.mall::lang.titles.payment_methods.create'
    redirect: 'webbook/mall/paymentmethods/update/:id'
    redirectClose: webbook/mall/paymentmethods
update:
    title: 'webbook.mall::lang.titles.payment_methods.edit'
    redirect: webbook/mall/paymentmethods
    redirectClose: webbook/mall/paymentmethods
