name: Brands
modelClass: WebBook\Mall\Models\Brand
form: $/webbook/mall/models/brand/fields.yaml
defaultRedirect: webbook/mall/brands
create:
    title: 'webbook.mall::lang.titles.brands.create'
    redirect: 'webbook/mall/brands/update/:id'
    redirectClose: webbook/mall/brands
update:
    title: 'webbook.mall::lang.titles.brands.edit'
    redirect: webbook/mall/brands
    redirectClose: webbook/mall/brands
preview: {  }
