title: 'webbook.mall::lang.common.notifications'
modelClass: WebBook\Mall\Models\Notification
list: $/webbook/mall/models/notification/columns.yaml
recordUrl: 'webbook/mall/notifications/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showSorting: 0
defaultSort:
    column: sort_order
    direction: asc
toolbar:
    search:
        prompt: 'backend::lang.list.search_prompt'
