name: 'webbook.mall::lang.common.notifications'
modelClass: WebBook\Mall\Models\Notification
form: $/webbook/mall/models/notification/fields.yaml
defaultRedirect: webbook/mall/notifications
create:
    title: 'webbook.mall::lang.titles.notifications.create'
    redirect: 'webbook/mall/notifications/update/:id'
    redirectClose: webbook/mall/notifications
update:
    title: 'webbook.mall::lang.titles.notifications.update'
    redirect: webbook/mall/notifications
    redirectClose: webbook/mall/notifications
