name: 'webbook.mall::lang.common.address'
modelClass: WebBook\Mall\Models\Address
form: $/webbook/mall/models/address/fields.yaml
defaultRedirect: webbook/mall/addresses
create:
    redirect: 'webbook/mall/addresses/update/:id'
    redirectClose: webbook/mall/addresses
update:
    redirect: webbook/mall/addresses
    redirectClose: webbook/mall/addresses
preview: {  }
