name: 'webbook.mall::lang.common.payment'
modelClass: WebBook\Mall\Models\PaymentLog
form: $/webbook/mall/models/paymentlog/fields.yaml
defaultRedirect: webbook/mall/paymentlogs
create:
    redirect: 'webbook/mall/paymentlogs/update/:id'
    redirectClose: webbook/mall/paymentlogs
update:
    redirect: webbook/mall/paymentlogs
    redirectClose: webbook/mall/paymentlogs
preview: {  }
