name: 'webbook.mall::lang.common.product'
modelClass: WebBook\Mall\Models\Product
form: $/webbook/mall/models/product/fields_edit.yaml
defaultRedirect: webbook/mall/products
create:
    title: 'webbook.mall::lang.titles.products.create'
    redirect: 'webbook/mall/products/update/:id'
    redirectClose: webbook/mall/products
    form: $/webbook/mall/models/product/fields_create.yaml
update:
    title: 'webbook.mall::lang.titles.products.update'
    redirect: webbook/mall/products
    redirectClose: webbook/mall/products
preview:
    title: 'webbook.mall::lang.titles.products.preview'
