dataSource: client
keyFrom: id
recordsPerPage: false
adding: false
deleting: false
searching: false
alias: pricetable
columns:
    type:
        title: 'type'
    original_id:
        title: 'original_id'
    name:
        title: webbook.mall::lang.common.product_or_variant
        readOnly: true
    stock:
        title: webbook.mall::lang.product.stock
    price:
        title: webbook.mall::lang.product.price
