name: 'webbook.mall::lang.common.property_groups'
modelClass: WebBook\Mall\Models\PropertyGroup
form: $/webbook/mall/models/propertygroup/fields.yaml
defaultRedirect: webbook/mall/propertygroups
create:
    title: 'webbook.mall::lang.titles.property_groups.create'
    redirect: 'webbook/mall/propertygroups/update/:id'
    redirectClose: webbook/mall/propertygroups
update:
    title: 'webbook.mall::lang.titles.property_groups.edit'
    redirect: webbook/mall/propertygroups
    redirectClose: webbook/mall/propertygroups
preview: {  }
