# ===================================
#  Relation Behavior Config
# ===================================

properties:
    label: 'webbook.mall::lang.common.property'
    deferredBinding: false
    view:
        list: $/webbook/mall/models/property/columns_pivot_legacy.yaml
        toolbarButtons: add|create|remove
        defaultSort:
            column: pivot[sort_order]
            direction: asc
    manage:
        form: $/webbook/mall/models/property/fields_pivot.yaml
        list: $/webbook/mall/models/property/columns.yaml
        showSearch: true
        recordsPerPage: 50
    pivot:
        form: $/webbook/mall/models/property/fields_pivot.yaml
    structure:
        showTree: false
        showReorder: true
        showSorting: false
        dragRow: true
