name: webbook.mall::lang.common.shipping_methods
modelClass: WebBook\Mall\Models\ShippingMethod
form: $/webbook/mall/models/shippingmethod/fields.yaml
defaultRedirect: webbook/mall/shippingmethods
create:
    title: 'webbook.mall::lang.titles.shipping_methods.create'
    redirect: 'webbook/mall/shippingmethods/update/:id'
    redirectClose: webbook/mall/shippingmethods
update:
    title: 'webbook.mall::lang.titles.shipping_methods.update'
    redirect: webbook/mall/shippingmethods
    redirectClose: webbook/mall/shippingmethods
preview:
    title: 'webbook.mall::lang.titles.shipping_methods.preview'
