name: 'webbook.mall::lang.common.custom_fields'
modelClass: WebBook\Mall\Models\CustomField
form: $/webbook/mall/models/customfield/fields.yaml
defaultRedirect: webbook/mall/customfields
create:
    redirect: 'webbook/mall/customfields/update/:id'
    redirectClose: webbook/mall/customfields
update:
    redirect: webbook/mall/customfields
    redirectClose: webbook/mall/customfields
preview: {  }
