title: 'webbook.mall::lang.common.custom_fields'
modelClass: WebBook\Mall\Models\CustomField
list: $/webbook/mall/models/customfield/columns.yaml
recordUrl: 'webbook/mall/customfields/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
