title: 'webbook.mall::lang.common.discounts'
modelClass: WebBook\Mall\Models\Discount
list: $/webbook/mall/models/discount/columns.yaml
recordUrl: 'webbook/mall/discounts/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
showSorting: 1
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
