name: 'webbook.mall::lang.common.discount'
modelClass: WebBook\Mall\Models\Discount
form: $/webbook/mall/models/discount/fields.yaml
defaultRedirect: webbook/mall/discounts
create:
    title: 'webbook.mall::lang.titles.discounts.create'
    redirect: 'webbook/mall/discounts/update/:id'
    redirectClose: webbook/mall/discounts
update:
    title: 'webbook.mall::lang.titles.discounts.update'
    redirect: webbook/mall/discounts
    redirectClose: webbook/mall/discounts
preview:
    title: 'webbook.mall::lang.titles.discounts.preview'
