name: webbook.mall::lang.price_category_settings.label
modelClass: WebBook\Mall\Models\PriceCategory
form: $/webbook/mall/models/pricecategory/fields.yaml
defaultRedirect: webbook/mall/pricecategories
create:
    title: webbook.mall::lang.titles.price_categories.create
    redirect: 'webbook/mall/pricecategories/update/:id'
    redirectClose: webbook/mall/pricecategories
update:
    title: webbook.mall::lang.titles.price_categories.update
    redirect: webbook/mall/pricecategories
    redirectClose: webbook/mall/pricecategories
preview: {  }
