name: 'webbook.mall::lang.common.customer_groups'
modelClass: WebBook\Mall\Models\CustomerGroup
form: $/webbook/mall/models/customergroup/fields.yaml
defaultRedirect: webbook/mall/customergroups
create:
    title: 'webbook.mall::lang.titles.customer_groups.create'
    redirect: 'webbook/mall/customergroups/update/:id'
    redirectClose: webbook/mall/customergroups
update:
    title: 'webbook.mall::lang.titles.customer_groups.update'
    redirect: webbook/mall/customergroups
    redirectClose: webbook/mall/customergroups
