# ===================================
#  Import/Export Behavior Config
# ===================================

export:
    title: webbook.mall::lang.titles.orders.export
    modelClass: WebBook\Mall\Models\OrderExport
    list: $/webbook/mall/models/order/export_columns.yaml
