name: webbook.mall::lang.currency_settings.label
modelClass: WebBook\Mall\Models\Currency
form: $/webbook/mall/models/currency/fields.yaml
defaultRedirect: webbook/mall/currencies
create:
    title: webbook.mall::lang.titles.currencies.create
    redirect: 'webbook/mall/currencies/update/:id'
    redirectClose: webbook/mall/currencies
update:
    title: webbook.mall::lang.titles.currencies.update
    redirect: webbook/mall/currencies
    redirectClose: webbook/mall/currencies
preview: {  }
