title: Services
modelClass: WebBook\Mall\Models\Service
list: $/webbook/mall/models/service/columns.yaml
recordUrl: 'webbook/mall/services/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
defaultSort:
    column: name
    direction: asc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
