options:
    label: 'webbook.mall::lang.services.option'
    view:
        list: $/webbook/mall/models/serviceoption/columns.yaml
        toolbarButtons: create|delete
        defaultSort: ['sort_order',  'ASC']
    manage:
        form: $/webbook/mall/models/serviceoption/fields.yaml
        recordsPerPage: 10
    structure:
        showTree: false
        showReorder: true
        showSorting: true
        dragRow: true

products:
    label: 'webbook.mall::lang.common.products'
    view:
        showSearch: true
        list: $/webbook/mall/models/product/columns.yaml
        toolbarButtons: add|remove
        recordUrl: 'webbook/mall/products/update/:id'
    pivot:
        form: $/webbook/mall/models/service/fields_pivot.yaml


taxes:
    label: 'webbook.mall::lang.common.taxes'
    view:
        list: $/webbook/mall/models/tax/columns.yaml
        toolbarButtons: add|create|remove
    manage:
        form: $/webbook/mall/models/tax/fields.yaml
        recordsPerPage: 10
    deferredBinding: true
