name: 'webbook.mall::lang.common.services'
modelClass: WebBook\Mall\Models\Service
form: $/webbook/mall/models/service/fields.yaml
defaultRedirect: webbook/mall/services
create:
    title: 'webbook.mall::lang.titles.services.create'
    redirect: 'webbook/mall/services/update/:id'
    redirectClose: webbook/mall/services
update:
    title: 'webbook.mall::lang.titles.services.update'
    redirect: webbook/mall/services
    redirectClose: webbook/mall/services
preview: {  }
