name: webbook.mall::lang.common.taxes
modelClass: WebBook\Mall\Models\Tax
form: $/webbook/mall/models/tax/fields.yaml
defaultRedirect: webbook/mall/taxes
create:
    title: 'webbook.mall::lang.titles.taxes.create'
    redirect: 'webbook/mall/taxes/update/:id'
    redirectClose: webbook/mall/taxes
update:
    title: 'webbook.mall::lang.titles.taxes.update'
    redirect: webbook/mall/taxes
    redirectClose: webbook/mall/taxes
