title: webbook.mall::lang.common.taxes
modelClass: WebBook\Mall\Models\Tax
list: $/webbook/mall/models/tax/columns.yaml
recordUrl: 'webbook/mall/taxes/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
