name: 'webbook.mall::lang.common.reviews'
modelClass: WebBook\Mall\Models\Review
form: $/webbook/mall/models/review/fields.yaml
defaultRedirect: webbook/mall/reviews
create:
    title: 'webbook.mall::lang.titles.reviews.create'
    redirect: 'webbook/mall/reviews/update/:id'
    redirectClose: webbook/mall/reviews
update:
    title: 'webbook.mall::lang.titles.reviews.update'
    redirect: webbook/mall/reviews
    redirectClose: webbook/mall/reviews
preview: {  }
