name: 'webbook.mall::lang.common.variants'
modelClass: WebBook\Mall\Models\Variant
form: $/webbook/mall/models/variant/fields.yaml
defaultRedirect: webbook/mall/variants
create:
    redirect: 'webbook/mall/variants/update/:id'
    redirectClose: webbook/mall/variants
update:
    redirect: webbook/mall/variants
    redirectClose: webbook/mall/variants
preview: {  }
