title: 'webbook.mall::lang.common.variants'
modelClass: WebBook\Mall\Models\Variant
list: $/webbook/mall/models/variant/columns.yaml
recordUrl: 'webbook/mall/variants/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
